### ISSUE TITLE
Often no results

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia-callhierarchy-extension#9]
There are many cases, where I see results in find references but not in call-hierarchy.
One instance: `cancellation.ts #checkCancelled()`.

<img width="997" alt="screen shot 2018-01-27 at 19 43 24" src="https://user-images.githubusercontent.com/372735/35475190-5d777a38-039a-11e8-8fa8-860c8a359332.png">
<img width="658" alt="screen shot 2018-01-27 at 19 43 01" src="https://user-images.githubusercontent.com/372735/35475191-5d8d8968-039a-11e8-9cb7-eefb1885704a.png">

**Comment by JanKoehnlein** [comment]
It is a bit worse than I expected:
We call `ls.definition()` with the caret location then take the resulting location to determine the symbol there. To calculate the callers, we take the start position of that symbol and call `ls.references()`. 
The problem is that the TS LS returns the full range of a callable, i.e. including all modifiers, bodies etc. If a symbol's range does not start with the name of the symbol (in the example above it starts with `export function`), `ls.references()` will return nothing at its `location.start`.
So for all symbol locations, we should instead use the position of the name inside the symbol's range to call `references` with. That may require loading the resource. Sounds a bit expensive, doesn't it?

Maybe we should go for a LSP extension, and calculate the call hierarchy on the server instead.

**Comment by JanKoehnlein** [comment]
Fixed
